events {}

http {
    # Define a zona de limite de requisições
    #limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/m;

    upstream webapi01 {
        server webapi01:8080;
    }

    upstream webapi02 {
        server webapi02:8080;
    }    
    
        
         log_format loki_json escape=json '{ "time": "$time_iso8601", '
                                              '"remote_addr": "$remote_addr", '
                                              '"body_bytes_sent": "$body_bytes_sent", '
                                              '"request_time": "$request_time", '
                                              '"status": "$status", '
                                              '"request": "$request", '
                                              '"request_method": "$request_method", '
                                              '"http_referrer": "$http_referer", '
                                              '"http_user_agent": "$http_user_agent", '
                                              '"http_x_forwarded_for": "$http_x_forwarded_for", '
                                              '"upstream_addr": "$upstream_addr", '
                                              '"upstream_status": "$upstream_status", '
                                              '"upstream_response_time": "$upstream_response_time", '
                                              '"request_length": "$request_length", '
                                              '"bytes_sent": "$bytes_sent", '
                                              '"connection": "$connection", '
                                              '"connection_requests": "$connection_requests", '
                                              '"pipe": "$pipe", '
                                              '"msec": "$msec", '
                                              '"request_id": "$request_id", '
                                              '"service_name": "nginx" }';
        
        access_log /var/log/nginx/access.log loki_json;
        access_log /dev/stdout;
        error_log /var/log/nginx/nginx.log;
        error_log /dev/stderr;
        
    server {
        listen 80;

        location /metrics {
            proxy_set_header service.name "Nginx";
            stub_status;
            allow all;
        }
        
        location /api/webapi01/ {
            set $auth_token $http_authorization;

            proxy_pass http://webapi01/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Path $request_uri;
            proxy_set_header X-Request-Source "Nginx";

            # Rate Limiting
#             limit_req zone=api_limit burst=5 nodelay;
#             limit_req_status 429;
        }

        location /api/webapi02/ {
            set $auth_token $http_authorization;

            proxy_pass http://webapi02/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Path $request_uri;
            proxy_set_header X-Request-Source "Nginx";

            # Rate Limiting
#             limit_req zone=api_limit burst=5 nodelay;
#             limit_req_status 429;
        }

        location /api/pokemon/ {
            proxy_pass http://pokeapi.co/api/v2/;

            # SSL
            proxy_ssl_verify on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;
            proxy_ssl_server_name on;
            proxy_ssl_trusted_certificate /etc/certificates/pokeapi-cert.crt;

            proxy_cache_valid 200 5m;
        }

        location / {
            return 204;
        }
    }
}